### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by fluca1978**
WHile working for the 2015 CPAN Pull Request Challenge, I looked at the excellent Test::Pod module and found a few things that, in my opinion, could be imroved.
Besides a few syntactic only things, most notably changes are related to the adoption of the Exporter module (instead of an hand written import routine) and a few enhancement in the internal method _is_perl, that is now coherent with the documentation.

### CODE REVIEW

**Comment by theory** [comment]
Thanks. Some comments:

> * Enabled "warnings" and placed an explicit return statement into the module import method.

Warnings are not necessary in such a stable module. No harm, really.

> * Removed a mixed use of low and high precedence "and" operators.

Seems reasonable.

> * Merged three regular expression in a single line.

Would be better written as `/[.](?:PL|p(?:[lm]|od)|t)$/`

> * Fixed a test in the internal `_is_perl` method to test for a (suspected) Perl file.

I think it should look at the file name and return 1 for a match *before* opening the file and reading the first line, as it did before. Silly to read in a line if you never examine it.

Also, I see you added a check for `.bat`. I don't know if that's necessary, but it would be better written as `/[.]bat$/i`.

Also, you don't need all the parentheses in that expression.

> * Removed the old-style import manual subroutine.

Adding the unnecessary overhead of the Exporter module and removing a call to `exported_to`.

**Comment by fluca1978** [comment]
I've "restored" the original logic of _is_perl, so that it checks for well known suffixes before opening the file. The rationale before my changes was that letting the file opening will test for readibility, that is not checked before calling pod_file_ok. It is not clear to me if having a not-readable file should be reported as an invalid pod file or skipped at all from the test.
In the meantime I've "fixed" all the regular expressions using your suggestions.

With regard to the usage of Exporter, it seems to me it produces less code for mere mortals (and removes the "no strict refs" that is something I tend to avoid). Of

**Comment by theory** [comment]
@rjbs points out that the existing `import` also allows a plan to be passed to it. There may well be code in the wild that depends on that, so I think we should leave it and *not* switch to Exporter.

**Comment by theory** [comment]
In fact, [it is used in the wild](http://grep.cpan.me/?q=use+Test::Pod%5Cs%5Ba-z%5D). (Thanks #rjbs!)

**Comment by fluca1978** [comment]
> @rjbs points out that the existing import also allows a plan to be passed to it.

Sorry for that silly error, I didn't notice it because all tests were passing. Should we add a forwarding method to get out plan information on Test::Pod from inner Test::Builder? This way we could also add a test to check that the plan (if specified) is correct.

Besides, do you believe there is something on this pull request that can be cherry picked? Otherwise please drop it at all.

**Comment by theory** [comment]
>  Should we add a forwarding method to get out plan information on Test::Pod from inner Test::Builder? This way we could also add a test to check that the plan (if specified) is correct.

I don't understand the question.

**Comment by fluca1978** [comment]
The original import method has a final $Test->plan(@_);' call. However seems to me no one test within the t directory will test for an effective plan, so maybe we should add a method to Test::Pod that allows us to retrieve the Test::Builder::has_plan value, so that we can also test ourselves for the plan to be set.
Of course the plan is working, what am I saying is that my stupid error was also driven by the fact that the plan is not tested at all within the module.

**Comment by theory** [comment]
I'm still not following. The point is not to retrieve the plan, but to declare it. Here's [an example](https://metacpan.org/source/SHOK/WebService-Gyazo-0.03/t/WebService_Gyazo_Image_testPOD.t):

    use Test::Pod tests => 1;

**Comment by fluca1978** [comment]
My point is that when I removed the import method, and therefore the Test::Builder->plan call, I was unable to see the error because no Test::Pod tests were reporting it. If we have a test that tries to use the module with a few plans we can test that the importing-with-plan functionality will always work.
But to be able to test it we have to forward Test::Builder->has_plan method.
Hope it is clear and useful.

**Comment by theory** [comment]
Oh, you want to be able to see what the plan gets set to from tests? Since Test::Builder is a singleton, I'm pretty sure you can just get that from `Test::Builder->new->expected_tests`.

**Comment by fluca1978** [comment]
Can you please close this pull request?
I'm going to create a new one with less changes and the correct (source) import behavior.

**Comment by theory** [comment]
Awesome. Thanks for taking this on!

**Pull request closed without merging**
